export const NAFDAC_DRUGS = [
  "Paracetamol 500mg", "Amoxicillin 500mg", "Ciprofloxacin 500mg", "Artemether/Lumefantrine 80/480mg",
  "Metronidazole 400mg", "Omeprazole 20mg", "Amlodipine 5mg", "Metformin 500mg", "Diclofenac 50mg",
  "Ibuprofen 400mg", "Azithromycin 500mg", "Ceftriaxone 1g Injection", "Gentamicin 80mg Injection",
  "Hydrochlorothiazide 25mg", "Lisinopril 10mg", "Atorvastatin 20mg", "Salbutamol Inhaler",
  "Prednisolone 5mg", "Dexamethasone 4mg", "Chlorpheniramine 4mg", "Promethazine 25mg",
  "Glibenclamide 5mg", "Insulin Soluble 100IU/ml", "Furosemide 40mg", "Spironolactone 25mg",
  "Warfarin 5mg", "Heparin 5000IU/ml", "Clopidogrel 75mg", "Aspirin 75mg", "Vitamin C 100mg",
  "Vitamin B Complex", "Folic Acid 5mg", "Ferrous Sulfate 200mg", "Calcium Carbonate 500mg",
  "Magnesium Trisilicate", "Aluminum Hydroxide", "Ranitidine 150mg", "Loperamide 2mg",
  "Bisacodyl 5mg", "Oral Rehydration Salts (ORS)", "Zinc Sulfate 20mg", "Albendazole 400mg",
  "Mebendazole 100mg", "Praziquantel 600mg", "Chloroquine 250mg", "Quinine Sulfate 300mg",
  "Doxycycline 100mg", "Tetracycline 250mg", "Erythromycin 250mg", "Clarithromycin 500mg",
  "Levofloxacin 500mg", "Nitrofurantoin 100mg", "Cotrimoxazole 480mg", "Fluconazole 150mg",
  "Ketoconazole 200mg", "Nystatin 100,000IU", "Griseofulvin 500mg", "Acyclovir 200mg",
  "Nevirapine 200mg", "Zidovudine 300mg", "Lamivudine 150mg", "Efavirenz 600mg",
  "Tenofovir 300mg", "Rifampicin 150mg", "Isoniazid 100mg", "Pyrazinamide 500mg",
  "Ethambutol 400mg", "Streptomycin 1g Injection", "Morphine 10mg", "Codeine 30mg",
  "Tramadol 50mg", "Pentazocine 30mg Injection", "Diazepam 5mg", "Lorazepam 2mg",
  "Amitriptyline 25mg", "Fluoxetine 20mg", "Haloperidol 5mg", "Chlorpromazine 100mg",
  "Phenobarbital 30mg", "Phenytoin 100mg", "Carbamazepine 200mg", "Sodium Valproate 200mg",
  "Levodopa/Carbidopa 100/25mg", "Atropine 1mg Injection", "Adrenaline 1mg Injection",
  "Digoxin 0.25mg", "Isosorbide Dinitrate 10mg", "Hydralazine 25mg", "Methyldopa 250mg",
  "Propranolol 40mg", "Atenolol 50mg", "Nifedipine 20mg", "Captopril 25mg",
  "Enalapril 5mg", "Losartan 50mg", "Simvastatin 20mg", "Gemfibrozil 600mg",
  "Beclomethasone Inhaler", "Theophylline 200mg", "Aminophylline 250mg Injection",
  "Cetirizine 10mg", "Loratadine 10mg", "Hydrocortisone 100mg Injection",
  "Silver Sulfadiazine Cream", "Neomycin/Bacitracin Ointment", "Clotrimazole Cream",
  "Benzyl Benzoate Lotion", "Permethrin Cream", "Povidone Iodine Solution",
  "Chlorhexidine Solution", "Ethyl Alcohol 70%", "Hydrogen Peroxide 6%",
  "Lidocaine 2% Injection", "Bupivacaine 0.5% Injection", "Ketamine 50mg/ml Injection",
  "Propofol 10mg/ml Injection", "Thiopental 500mg Injection", "Suxamethonium 50mg/ml Injection",
  "Vecuronium 4mg Injection", "Neostigmine 0.5mg/ml Injection", "Naloxone 0.4mg/ml Injection",
  "Flumazenil 0.1mg/ml Injection", "Oxytocin 10IU/ml Injection", "Ergometrine 0.5mg Injection",
  "Misoprostol 200mcg", "Magnesium Sulfate 50% Injection", "Nifedipine 10mcg",
  "Ethinylestradiol/Levonorgestrel", "Medroxyprogesterone Injection", "Condoms",
  "Intrauterine Device (IUD)", "Timolol 0.5% Eye Drops", "Atropine 1% Eye Drops",
  "Gentamicin 0.3% Eye Drops", "Chloramphenicol 0.5% Eye Drops", "Dexamethasone 0.1% Eye Drops",
  "Acetazolamide 250mg", "Pilocarpine 2% Eye Drops", "Latanoprost 0.005% Eye Drops",
  "Artificial Tears", "Normal Saline 0.9% 500ml", "Dextrose 5% 500ml",
  "Ringer's Lactate 500ml", "Dextrose Saline 500ml", "Potassium Chloride Injection",
  "Sodium Bicarbonate 8.4% Injection", "Water for Injection 10ml", "Oxygen",
  "Nitrous Oxide", "Halothane", "Isoflurane", "Sevoflurane",
  // Adding more to reach ~400 (simulated with variations and common Nigerian brands/generics)
  "Artesunate 60mg Injection", "Artesunate/Amodiaquine", "Dihydroartemisinin/Piperaquine",
  "Sulfadoxine/Pyrimethamine", "Lumefantrine Suspension", "Amoxicillin/Clavulanate 625mg",
  "Amoxicillin/Clavulanate 1g", "Cefuroxime 250mg", "Cefuroxime 500mg", "Cefixime 400mg",
  "Ceftazidime 1g Injection", "Cefotaxime 1g Injection", "Meropenem 1g Injection",
  "Imipenem/Cilastatin 500mg", "Vancomycin 500mg Injection", "Linezolid 600mg",
  "Piperacillin/Tazobactam 4.5g", "Amikacin 500mg Injection", "Clindamycin 300mg",
  "Roxithromycin 150mg", "Telithromycin 400mg", "Moxifloxacin 400mg", "Ofloxacin 200mg",
  "Norfloxacin 400mg", "Tinidazole 500mg", "Secnidazole 1g", "Diloxanide Furoate 500mg",
  "Nitazoxanide 500mg", "Ivermectin 3mg", "Albendazole Suspension", "Pyrantel Pamoate",
  "Niclosamide 500mg", "Terbinafine 250mg", "Itraconazole 100mg", "Voriconazole 200mg",
  "Amphotericin B Injection", "Caspofungin Injection", "Valacyclovir 500mg",
  "Ganciclovir 500mg Injection", "Oseltamivir 75mg", "Ribavirin 200mg",
  "Abacavir 300mg", "Didanosine 250mg", "Stavudine 30mg", "Lopinavir/Ritonavir",
  "Atazanavir 300mg", "Darunavir 600mg", "Raltegravir 400mg", "Dolutegravir 50mg",
  "Entecavir 0.5mg", "Adefovir 10mg", "Telbivudine 600mg", "Sofosbuvir 400mg",
  "Ledipasvir/Sofosbuvir", "Daclatasvir 60mg", "Interferon Alpha Injection",
  "Cyclophosphamide 50mg", "Methotrexate 2.5mg", "Fluorouracil 500mg Injection",
  "Doxorubicin 50mg Injection", "Vincristine 1mg Injection", "Paclitaxel 100mg Injection",
  "Cisplatin 50mg Injection", "Tamoxifen 20mg", "Anastrozole 1mg", "Bicalutamide 50mg",
  "Imatinib 100mg", "Rituximab Injection", "Trastuzumab Injection", "Erythropoietin Injection",
  "Filgrastim Injection", "Cyclosporine 100mg", "Azathioprine 50mg", "Mycophenolate Mofetil 500mg",
  "Tacrolimus 1mg", "Sirolimus 1mg", "Thalidomide 100mg", "Leflunomide 20mg",
  "Infliximab Injection", "Etanercept Injection", "Adalimumab Injection",
  "Hydroxyzine 25mg", "Diphenhydramine 25mg", "Cyproheptadine 4mg", "Fexofenadine 120mg",
  "Desloratadine 5mg", "Montelukast 10mg", "Zafirlukast 20mg", "Tiotropium Inhaler",
  "Ipratropium Inhaler", "Fluticasone Inhaler", "Budesonide Inhaler", "Formoterol Inhaler",
  "Salmeterol Inhaler", "Doxapram Injection", "Caffeine Citrate Injection",
  "Codeine Linctus", "Guaifenesin Syrup", "Dextromethorphan Syrup", "Bromhexine Syrup",
  "Ammonium Chloride Syrup", "Diphenoxylate/Atropine", "Hyoscine Butylbromide 10mg",
  "Mebeverine 135mg", "Alverine Citrate 60mg", "Domperidone 10mg", "Metoclopramide 10mg",
  "Ondansetron 8mg", "Granisetron 1mg", "Aprepitant 125mg", "Lactulose Syrup",
  "Liquid Paraffin", "Senna Tablets", "Castor Oil", "Glycerin Suppositories",
  "Mesalazine 500mg", "Sulfasalazine 500mg", "Hydrocortisone Enema", "Ursodeoxycholic Acid 250mg",
  "Pancreatin", "Cholestyramine", "Telmisartan 40mg", "Valsartan 80mg",
  "Irbesartan 150mg", "Candesartan 8mg", "Olmesartan 20mg", "Doxazosin 4mg",
  "Terazosin 5mg", "Prazosin 1mg", "Carvedilol 6.25mg", "Nebivolol 5mg",
  "Bisoprolol 5mg", "Verapamil 80mg", "Diltiazem 60mg", "Felodipine 5mg",
  "Lercanidipine 10mg", "Isradipine 2.5mg", "Minoxidil 5mg", "Sodium Nitroprusside Injection",
  "Glyceryl Trinitrate Spray", "Pentaerythritol Tetranitrate", "Trimetazidine 20mg",
  "Ivabradine 5mg", "Ranolazine 500mg", "Amiodarone 200mg", "Sotalol 80mg",
  "Flecainide 100mg", "Propafenone 150mg", "Mexiletine 150mg", "Quinidine 200mg",
  "Procainamide Injection", "Lidocaine Injection (Anti-arrhythmic)", "Adenosine Injection",
  "Dobutamine Injection", "Dopamine Injection", "Noradrenaline Injection",
  "Phenylephrine Injection", "Ephedrine Injection", "Milrinone Injection",
  "Levosimendan Injection", "Streptokinase Injection", "Alteplase Injection",
  "Tenecteplase Injection", "Urokinase Injection", "Tranexamic Acid 500mg",
  "Protamine Sulfate Injection", "Phytomenadione (Vitamin K1) Injection",
  "Desmopressin Nasal Spray", "Factor VIII Concentrate", "Factor IX Concentrate",
  "Fresh Frozen Plasma", "Platelet Concentrate", "Whole Blood", "Packed Red Cells",
  "Albumin Human 20%", "Dextran 40", "Gelatin Infusion", "Hydroxyethyl Starch",
  "Mannitol 20% 250ml", "Acetazolamide Injection", "Ethacrynic Acid 50mg",
  "Torsemide 10mg", "Amiloride 5mg", "Triamterene 50mg", "Eplerenone 25mg",
  "Tolvaptan 15mg", "Desmopressin 0.1mg", "Terlipressin Injection", "Somatostatin Injection",
  "Octreotide Injection", "Glucagon Injection", "Diazoxide Injection",
  "Propylthiouracil 50mg", "Carbimazole 5mg", "Methimazole 5mg", "Lugol's Iodine",
  "Radioactive Iodine (I-131)", "Levothyroxine 50mcg", "Liothyronine 20mcg",
  "Fludrocortisone 0.1mg", "Methylprednisolone 40mg Injection", "Triamcinolone 40mg Injection",
  "Betamethasone 0.5mg", "Testosterone Enanthate Injection", "Nandrolone Decanoate Injection",
  "Stanozolol 2mg", "Danazol 200mg", "Estradiol 2mg", "Conjugated Estrogens",
  "Progesterone 100mg", "Norethisterone 5mg", "Levonorgestrel 0.75mg", "Desogestrel 75mcg",
  "Gestodene/Ethinylestradiol", "Cyproterone Acetate 50mg", "Clomiphene Citrate 50mg",
  "Tamoxifen 10mg", "Letrozole 2.5mg", "Exemestane 25mg", "Goserelin Injection",
  "Leuprolide Injection", "Triptorelin Injection", "Human Chorionic Gonadotropin (HCG)",
  "Menopausal Gonadotropin (HMG)", "Follicle Stimulating Hormone (FSH)",
  "Bromocriptine 2.5mg", "Cabergoline 0.5mg", "Quinagolide 75mcg", "Somatropin Injection",
  "Desmopressin 10mcg/ml Injection", "Vasopressin Injection", "Calcitonin Injection",
  "Teriparatide Injection", "Alendronate 70mg", "Risedronate 35mg", "Ibandronate 150mg",
  "Zoledronic Acid Injection", "Raloxifene 60mg", "Strontium Ranelate",
  "Cinacalcet 30mg", "Sevelamer 800mg", "Lanthanum Carbonate 500mg", "Calcitriol 0.25mcg",
  "Alfacalcidol 1mcg", "Cholecalciferol (Vitamin D3) 1000IU", "Ergocalciferol (Vitamin D2)",
  "Vitamin A 50,000IU", "Vitamin E 400IU", "Vitamin B1 (Thiamine) 100mg",
  "Vitamin B2 (Riboflavin) 5mg", "Vitamin B6 (Pyridoxine) 50mg", "Vitamin B12 (Cyanocobalamin)",
  "Nicotinamide 50mg", "Pantothenic Acid", "Biotin", "Multivitamin Syrup",
  "Iron/Folic Acid Syrup", "Zinc/ORS Co-pack", "Potassium Citrate Mixture",
  "Sodium Citrate Mixture", "Ammonium Chloride Mixture", "Ipecacuanha Emetic",
  "Activated Charcoal", "Universal Antidote", "Dimercaprol Injection",
  "Penicillamine 250mg", "Deferoxamine Injection", "Deferiprone 500mg",
  "Deferasirox 250mg", "Edetate Calcium Disodium", "Sodium Thiosulfate Injection",
  "Methylene Blue Injection", "Pralidoxime Injection", "Obidoxime Injection",
  "Snake Antivenom (Polyvalent)", "Rabies Vaccine", "Rabies Immunoglobulin",
  "Tetanus Toxoid", "Tetanus Immunoglobulin", "Diphtheria Antitoxin",
  "Gas Gangrene Antitoxin", "Botulinum Antitoxin", "BCG Vaccine",
  "Oral Polio Vaccine (OPV)", "Inactivated Polio Vaccine (IPV)", "Measles Vaccine",
  "MMR Vaccine", "Yellow Fever Vaccine", "Hepatitis B Vaccine",
  "Hepatitis A Vaccine", "Typhoid Vaccine", "Meningococcal Vaccine",
  "Pneumococcal Vaccine", "Haemophilus Influenzae Type B (Hib) Vaccine",
  "Rotavirus Vaccine", "Human Papillomavirus (HPV) Vaccine", "Cholera Vaccine",
  "Influenza Vaccine", "Varicella Vaccine", "Japanese Encephalitis Vaccine",
  "Tick-borne Encephalitis Vaccine", "DPT Vaccine", "Pentavalent Vaccine (DPT-HepB-Hib)",
  "Hexavalent Vaccine", "TdaP Vaccine", "Smallpox Vaccine", "Anthrax Vaccine",
  "Plague Vaccine", "Tularemia Vaccine", "Q Fever Vaccine"
];

export const LAB_TESTS = [
  "Full Blood Count (FBC)", "Packed Cell Volume (PCV)", "Hemoglobin (Hb) Level",
  "White Blood Cell (WBC) Count & Differential", "Platelet Count", "Erythrocyte Sedimentation Rate (ESR)",
  "Blood Group & Genotype", "Malaria Parasite (MP) Test", "Widal Test (Typhoid)",
  "Urinalysis (Dipstick & Microscopy)", "Urine Culture & Sensitivity", "Stool Microscopy",
  "Stool Culture & Sensitivity", "Fast Blood Sugar (FBS)", "Random Blood Sugar (RBS)",
  "Glycated Hemoglobin (HbA1c)", "Lipid Profile (Cholesterol, HDL, LDL, Triglycerides)",
  "Liver Function Test (LFT)", "Kidney Function Test (E/U/Cr)", "Serum Electrolytes (Na+, K+, Cl-, HCO3-)",
  "Uric Acid Test", "Calcium, Phosphorus, Magnesium", "Thyroid Function Test (T3, T4, TSH)",
  "Prostate Specific Antigen (PSA)", "Pregnancy Test (Urine & Serum HCG)", "Hepatitis B Surface Antigen (HBsAg)",
  "Hepatitis C Virus (HCV) Antibody", "HIV Screening (Rapid & ELISA)", "Syphilis (VDRL/RPR)",
  "High Vaginal Swab (HVS) Microscopy, Culture & Sensitivity", "Urethral Swab MCS", "Wound Swab MCS",
  "Semen Analysis", "Cerebrospinal Fluid (CSF) Analysis", "Pleural Fluid Analysis",
  "Ascitic Fluid Analysis", "Synovial Fluid Analysis", "Skin Snip for Microfilaria",
  "Sputum for AFB (Tuberculosis)", "GeneXpert MTB/RIF", "COVID-19 PCR/Rapid Antigen",
  "C-Reactive Protein (CRP)", "Rheumatoid Factor (RF)", "Antistreptolysin O (ASO) Titre",
  "Blood Culture & Sensitivity", "Coagulation Profile (PT, PTT, INR)", "Bleeding & Clotting Time",
  "G6PD Screening", "Sickling Test", "Reticulocyte Count", "Peripheral Blood Film",
  "Bone Marrow Aspiration & Biopsy", "Alpha-Fetoprotein (AFP)", "Carcinoembryonic Antigen (CEA)",
  "CA-125 (Ovarian Cancer Marker)", "CA-15-3 (Breast Cancer Marker)", "CA-19-9 (Pancreatic Cancer Marker)",
  "Beta-HCG (Tumor Marker)", "Serum Iron & Ferritin", "Total Iron Binding Capacity (TIBC)",
  "Vitamin B12 & Folate Assay", "Serum Cortisol", "Prolactin Level", "Follicle Stimulating Hormone (FSH)",
  "Luteinizing Hormone (LH)", "Estradiol Level", "Progesterone Level", "Testosterone Level",
  "Growth Hormone Assay", "Parathyroid Hormone (PTH)", "Troponin I/T (Cardiac Markers)",
  "CK-MB", "Myoglobin", "Brain Natriuretic Peptide (BNP)", "D-Dimer Test",
  "Serum Protein Electrophoresis", "Bence-Jones Protein (Urine)", "Antinuclear Antibody (ANA)",
  "Anti-dsDNA", "Lupus Erythematosus (LE) Cells", "Coombs Test (Direct & Indirect)",
  "Blood Cross-matching", "Mantoux Test", "Gram Stain", "Giemsa Stain",
  "Ziehl-Neelsen (ZN) Stain", "KOH Mount for Fungi", "Fungal Culture",
  "Pap Smear", "Fine Needle Aspiration Cytology (FNAC)", "Histopathology (Biopsy)",
  "Chest X-Ray", "Abdominal X-Ray", "Pelvic X-Ray", "Skull X-Ray",
  "Spinal X-Ray (Cervical, Thoracic, Lumbar)", "Limb X-Ray", "Dental X-Ray",
  "Abdominal Ultrasound", "Pelvic Ultrasound", "Obstetric Ultrasound (Antenatal)",
  "Transvaginal Ultrasound", "Breast Ultrasound", "Scrotal Ultrasound",
  "Thyroid Ultrasound", "Echocardiogram (ECG)", "Electrocardiogram (EKG)",
  "CT Scan (Brain, Abdomen, Chest)", "MRI Scan (Brain, Spine, Joints)", "Mammography"
];
